- name: Install htop.
  hosts: all
  become: yes
  tasks:
    - name: Installing htop
      apt:
        name: htop
        state: present

- name: Install Docker.
  hosts: all
  become: yes
  tasks:
    - name: Installing curl, ca-certificates, gnupg
      apt:
        name:
          - curl
          - ca-certificates
          - gnupg
        update_cache: yes

    - name: Create folder.
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory

    - name: Docker repository key.
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc

    - name: Add Docker Repository
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/{{ ansible_distribution | lower }}/ {{ ansible_distribution_release }} stable"
        state: present
        filename: docker

    - name: Install docker things.
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        update_cache: yes

    - name: Add user to Docker group.
      user:
        name: leonlewiz
        groups: docker
        append: yes

    - name: Docker services.
      service:
        name: docker
        state: started
        enabled: yes



- name: Clone repository.
  hosts: all
  become: yes
  tasks:
    - name: Git clone.
      git:
        repo: https://github.com/LeonLewiz/my-nginx-site.git
        dest: /var/www/html/my-nginx-site

    - name: Copy secrets to managed nodes.
      copy:
        src: files/.env
        dest: /var/www/html/my-nginx-site/.env

    - name: Compose the containers.
      shell: cd /var/www/html/my-nginx-site && docker compose up -d --build
