name: CI

on:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run commands
        run: |
          echo "CI настроен."
          ls -la

      - name: Build an image.
        run: |
          docker build -t my-test-image ./backend

      - name: Send to github packages.
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          # Выводит токен гитхаба через echo и через | передает в след. команду, которая логинит меня в github packages.
          docker tag my-test-image ghcr.io/leonlewiz/my-nginx-site/my-test-image
          # Метка чтоб пуш нормально работал, ругается что ее нет.
          
          docker push ghcr.io/leonlewiz/my-nginx-site/my-test-image:latest
          # Пушит образ докера на склад, {{ github.repository }} (подставляет имя) не сработал, в нике есть заглавные буквы из-за этого ошибка.

      - name: Deploy to VM with ssh.
        uses: appleboy/ssh-action@v1
        with:
          host: 192.168.13.130       # IP твоей виртуалки
          username: leonlewiz        # юзер на виртуалке (например leon)
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/html/my-nginx-site
            docker pull ghcr.io/leonlewiz/my-nginx-site/my-test-image:latest
            docker compose up -d --force-recreate
