name: CI

on:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-server-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run commands
        run: |
          echo "CI configured"
          ls -la
